### PR TITLE
navbar redesign

### LINKED ISSUE #372: Navbar redesign
As a developer point of view I would like to redesign navbar.
 I make sure all menu will be shown.
 and also want to add navbar hide and show functionality at certain height which looks nice than the sticky navbar.

### PR DESCRIPTION
**Pull request by BhartiNagpure**
# Description

I have redesign the navbar as u share the design for desktop view as well as for mobile view.

## Screenshots

Screenshot 2023-07-18 174646
Screenshot 2023-07-18 174632

## Checklist

- [x] Tests have been added or updated to cover the changes
- [x] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by BhartiNagpure** [comment]
@swapnilsparsh I'm done with my work please review it.

**Comment by BhartiNagpure** [comment]
> Check the image which I share for Navbar image. Ambassador, WebDev, Games, etc will not be shown it is showing right now. You have to make it like I have shared the image.

But where it is not shown in the image .

**Comment by swapnilsparsh** [comment]
> > Check the image which I share for Navbar image. Ambassador, WebDev, Games, etc will not be shown it is showing right now. You have to make it like I have shared the image.
> 
> But where it is not shown in the image, you only mark the number to replace .

Check the icons which are showing below.

**Comment by BhartiNagpure** [comment]
> > > Check the image which I share for Navbar image. Ambassador, WebDev, Games, etc will not be shown it is showing right now. You have to make it like I have shared the image.
> > 
> > 
> > But where it is not shown in the image, you only mark the number to replace .
> 
> Check the icons which are showing below.

Can you mark it again I will make it correct.

**Comment by swapnilsparsh** [comment]
> > > > Check the image which I share for Navbar image. Ambassador, WebDev, Games, etc will not be shown it is showing right now. You have to make it like I have shared the image.
> > > 
> > > 
> > > But where it is not shown in the image, you only mark the number to replace .
> > 
> > 
> > Check the icons which are showing below.
> 
> Can you mark it again I will make it correct.

@BhartiNagpure Check [here](https://github.com/swapnilsparsh/DevEmpire/issues/372#issuecomment-1637196570)

**Pull request closed without merging**
