### PR TITLE
Ambassador section's UI improved

### LINKED ISSUE #294: Enhance Ui of the Ambassador page.
I would like to change the ui of the ambassador  page by adding some cool effects and also would like to change the ui of the cards too.
So,please assign this to me under Gssoc'23.
Screenshot 2023-06-20 142233

### PR DESCRIPTION
**Pull request by Pragati-3003**
I have updated the UI of the Ambassador page ,please check and inform me if you wanna any other changes.
Fixes #294

https://github.com/swapnilsparsh/DevEmpire/assets/132778037/d78ea093-8f5e-457d-9945-410a758c84cb

- [ x] Tests have been added or updated to cover the changes
- [x ] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [ x] All tests are passing

### CODE REVIEW

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
Great efforts but when on hovering the card the animation is not looking good. Try for something else.
Also "Ambassador" heading shading is also not looking good.

**Comment by Pragati-3003** [comment]
> Great efforts but when on hovering the card the animation is not looking good. Try for something else. Also "Ambassador" heading shading is also not looking good.

okie.
I will modify the page as per your requirements.

**Comment by Pragati-3003** [comment]
> Great efforts but when on hovering the card the animation is not looking good. Try for something else. Also "Ambassador" heading shading is also not looking good.

Hey, I have changed the css .Please change and inform me if you wanna any other changes.

**Review by swapnilsparsh — COMMENTED** [review]
Heading is not center aligned. also please change the animation on hover

**Comment by Pragati-3003** [comment]
> Heading is not center aligned. also please change the animation on hover

Screenshot 2023-06-22 194707
Hey,  I have changed the hover effects  and adjusted the alignment of the heading  ,so, please check and merge also lemme know if you wanna any other hover effects.

**Comment by swapnilsparsh** [comment]
@Pragati-3003 I am still able to see heading is not aligned and the same previous animation. You can check on the deploy preview of the netlift which is there above.

**Comment by Pragati-3003** [comment]
> @Pragati-3003 I am still able to see heading is not aligned and the same previous animation. You can check on the deploy preview of the netlift which is there above.

Hi, I checked the preview of the netlify and noticed that the heading is centrally aligned. Additionally, could you please clarify the specific hover effects you would like? In the current deployment, I have implemented an effect where the card scales up and the box-shadow changes. Are you expecting flipper-like effects or any other specific effects? Please provide clarification so that I can make the necessary changes accordingly.

**Comment by Pragati-3003** [comment]
> @Pragati-3003 I am still able to see heading is not aligned and the same previous animation. You can check on the deploy preview of the netlift which is there above.

Hi, I checked the preview of the netlify and noticed that the heading is centrally aligned. Additionally, could you please clarify the specific hover effects you would like? In the current deployment, I have implemented an effect where the card scales up and the box-shadow changes. Are you expecting flipper-like effects or any other specific effects? Please provide clarification so that I can make the necessary changes accordingly.

**Comment by Pragati-3003** [comment]
> @Pragati-3003 I am still able to see heading is not aligned and the same previous animation. You can check on the deploy preview of the netlift which is there above.

Hi, I checked the preview of the netlify and noticed that the heading is centrally aligned. Additionally, could you please clarify the specific hover effects you would like? In the current deployment, I have implemented an effect where the card scales up and the box-shadow changes. Are you expecting flipper-like effects or any other specific effects? Please provide clarification so that I can make the necessary changes accordingly.

**Comment by Pragati-3003** [comment]
> @Pragati-3003 I am still able to see heading is not aligned and the same previous animation. You can check on the deploy preview of the netlift which is there above.


Hi, I checked the preview of the netlify and noticed that the heading is centrally aligned. Additionally, could you please clarify the specific hover effects you would like? In the current deployment, I have implemented an effect where the card scales up and the box-shadow changes. Are you expecting flipper-like effects or any other specific effects? Please provide clarification so that I can make the necessary changes accordingly.

**Comment by Pragati-3003** [comment]
> @Pragati-3003 I am still able to see heading is not aligned and the same previous animation. You can check on the deploy preview of the netlift which is there above.


Hi, I checked the preview of the netlify and noticed that the heading is centrally aligned. Additionally, could you please clarify the specific hover effects you would like? In the current deployment, I have implemented an effect where the card scales up and the box-shadow changes. Are you expecting flipper-like effects or any other specific effects? Please provide clarification so that I can make the necessary changes accordingly.
Screenshot 2023-06-23 162435

**Comment by swapnilsparsh** [comment]
@Pragati-3003 I am getting this, can you verify once.
image

**Comment by Pragati-3003** [comment]
> @Pragati-3003 I am getting this, can you verify once. image
 
Nope , on my screen it was shown perfectly.

image

**Comment by swapnilsparsh** [comment]
@Pragati-3003 getting this 
image

**Comment by Pragati-3003** [comment]
> @Pragati-3003 getting this image

okie, I'll make it responsive

**Comment by Pragati-3003** [comment]
> @Pragati-3003 getting this image
I have made some changes ,please look .

**Pull request closed without merging**
