### PR TITLE
Updated 404 page

### PR DESCRIPTION
**Pull request by rockingrohit9639**
Fix: #102

### CODE REVIEW

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
Great work, SVG has been fixed but you have changed the CSS of the back to the home button.
Keep the same CSS for back to home button as of Explore button.

**Comment by rockingrohit9639** [comment]
@swapnilsparsh 
Should it be like this ??

image

**Comment by swapnilsparsh** [comment]
> @swapnilsparsh 
> Should it be like this ??
> 
> image
> 

Yes like the Explore Button CSS

**Comment by rockingrohit9639** [comment]
@swapnilsparsh I have updated the style.

**Comment by swapnilsparsh** [comment]
@rockingrohit9639 Any update??

**Comment by rockingrohit9639** [comment]
> @rockingrohit9639 Any update??

Sorry, bro, I was busy with my exams. Will update the changes today.

**Comment by swapnilsparsh** [comment]
@rockingrohit9639  Thank you for your contribution. Looking forward to more such amazing contributions 🥂

**Pull request merged**
