### PR TITLE
Illaf

### LINKED ISSUE #333: The programs page looks a lot crowded
**Is your feature request related to a problem? Please describe.**
The programs page has the headings, buttons  and the main content a lot closer.

**Describe the solution you'd like**
The content can be separated a bit so that the website looks organised . This can be done through basic UI improvements.
Screenshot (33)

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by Illaf**
# Description
I have formatted the layout of programs page so that it looks more clean and easily understandable. Please review and merge this pr so that I can apply animations effects on this page according to issue #332 
Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

## Fixes #333

Replace `issue_no` with the issue number which is fixed in this PR

## Screenshots
Screenshot (41)

## Checklist

- [x] Tests have been added or updated to cover the changes
- [x] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by Illaf** [comment]
@isaacplmann @chris--jones  Please review this pull request

**Comment by swapnilsparsh** [comment]
@Illaf there are no changes in layout.

**Comment by Illaf** [comment]
@swapnilsparsh by layout I mean the designing and spacing that I have added to the programs page as i described in the issue. If you want further changes then you can specify.

**Comment by swapnilsparsh** [comment]
> @swapnilsparsh by layout I mean the designing and spacing that I have added to the programs page as i described in the issue. If you want further changes then you can specify.

As you suggested that page was looking crowded so just by adding margins and padding to the current layout doesnt create a large differene.

**Comment by Illaf** [comment]
@swapnilsparsh Please if you can specify the changes that you want so it will be easier for me to do the changes.
If you agree then I can plan a new design for the page. What do you say?

**Comment by swapnilsparsh** [comment]
> @swapnilsparsh Please if you can specify the changes that you want so it will be easier for me to do the changes. If you agree then I can plan a new design for the page. What do you say?

Plan a new design.

**Comment by Illaf** [comment]
> > @swapnilsparsh Please if you can specify the changes that you want so it will be easier for me to do the changes. If you agree then I can plan a new design for the page. What do you say?
> 
> Plan a new design.

Okay👍

**Pull request closed without merging**
