### PR TITLE
Subheadings added to each page

### PR DESCRIPTION
**Pull request by udz-codes**
## Subheadings are added to each page under the title. Screenshots are added below for reference.

image
image
image
image

### CODE REVIEW

**Comment by swapnilsparsh** [comment]
@udz-codes Try to put the subheading on the right side of the heading as a paragraph.

**Comment by udz-codes** [comment]
@swapnilsparsh
I don't understand what are the conflicts with the JSTookKits.js file, can you take a look?

**Comment by udz-codes** [comment]
> @udz-codes Try to put the subheading on the right side of the heading as a paragraph and please resolve the conflicts also.

Okay, I will try that.

**Comment by udz-codes** [comment]
> @udz-codes Try to put the subheading on the right side of the heading as a paragraph and please resolve the conflicts also.

That would not work in the case of **Open Source Programs** page, as there is no space to the right of that heading.

image

**Pull request closed without merging**
