### PR TITLE
Grammatical and spelling issue solved

### PR DESCRIPTION
**Pull request by HimanshuNarware**
Grammatical and spelling issue solved, All the possible grammatical and spelling errors are solved
According to your instructions

### CODE REVIEW

**Comment by JawHawk** [comment]
@swapnilsparsh  Pls look into this quickly. The commit has not properly resolved conflicts in files such as ambassador.js, the project doesn't even run in development mode. Have to revert it back.

**Comment by swapnilsparsh** [comment]
> @swapnilsparsh  Pls look into this quickly. The commit has not properly resolved conflicts in files such as ambassador.js, the project doesn't even run in development mode. Have to revert it back.
> image
> 

Can you make a quick fix for this thing? Thank you for pointing this out. Great finding 🌟

**Comment by JawHawk** [comment]
Yes, I can but will be able to do it tomorrow early morning. Is it okay ?

**Comment by swapnilsparsh** [comment]
> Yes, I can but will be able to do it tomorrow early morning. Is it okay ?
> 
> 

Ok 👍🏻

**Comment by HimanshuNarware** [comment]
> > @swapnilsparsh  Pls look into this quickly. The commit has not properly resolved conflicts in files such as ambassador.js, the project doesn't even run in development mode. Have to revert it back.
> > image
> 
> Can you make a quick fix for this thing? Thank you for pointing this out. Great finding 🌟

OK sir

**Pull request merged**
