### PR TITLE
Add one more Open Source contribution program

### PR DESCRIPTION
**Pull request by mahak-dev**
Hello 
I added one more open source fellowship program name is XROS. Please add all my contributions under the GSSOC'2023.

### CODE REVIEW

**Comment by swapnilsparsh** [comment]
@mahak-dev Can you mention the issue which is assigned to you ?

**Comment by mahak-dev** [comment]
no issues is assigned to me its just a suggestion that I have added.

**Comment by swapnilsparsh** [comment]
@mahak-dev I can merge the PR but as it is just a small contribution of adding a  program, I can not provide you any level tag. Is it okay then let me know then I will merge the PR

**Comment by mahak-dev** [comment]
Sure

**Comment by mahak-dev** [comment]
@swapnilsparsh you can assign me any other task.

**Comment by swapnilsparsh** [comment]
> @swapnilsparsh you can assign me any other task.

You can look out for other issues else create a new issue if founf any

**Comment by mahak-dev** [comment]
sure.

**Pull request closed without merging**
