### PR TITLE
Tried to improved search UI, added search icon, increased width

### LINKED ISSUE #15: Improve search input UI
The search input's width looks insufficient. Seaching longer keywords can be a little harder. 
It would be better to increase the width and improve the UI.

### PR DESCRIPTION
**Pull request by tnmyk**
Closes #15

### CODE REVIEW

**Comment by tnmyk** [comment]
Lemme know if any more changes are necessary :D

**Comment by swapnilsparsh** [comment]
@tnmyk Please resolve the conflicts.

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
**Please Fix this** 
Annotation 2021-10-02 130346

**Comment by tnmyk** [comment]
Can you refresh the page? It shouldn't be there now

**Comment by swapnilsparsh** [comment]
@tnmyk Thank you for your contribution. Looking forward to more such amazing contributions 🥂

**Pull request merged**
