### PR TITLE
Fixed Preloader

### PR DESCRIPTION
**Pull request by Nishitbaria**
**GitHub Pull Request**

Fixes ISSUE #418
**Description:**

I have fixed the issue with the preloader in the DevEmpire website by correcting the image path that was causing the preloader to malfunction. The preloader was failing to display due to an incorrect image path reference. This pull request addresses the issue and ensures that the preloader is displayed as expected.

**Changes Made:**

I updated the image path in the preloader component to point to the correct location of the loading image. The previous path was causing the preloader to not show up, which has now been resolved by providing the accurate image path.

**Testing:**

I have tested the preloader thoroughly on different devices and browsers to confirm that the fix has successfully resolved the issue. The preloader now displays correctly during page loading.

**Impact:**

This fix significantly improves the user experience on the DevEmpire website by ensuring that the preloader works as intended. Users will now see the preloader while the content is being loaded, reducing confusion and enhancing the overall perception of the website's performance.

image

**Screenshots:**

(Optional: If applicable, you can attach screenshots demonstrating the preloader displaying correctly after the fix.)

I appreciate your review and feedback on this fix. Please let me know if any further adjustments are needed or if there are any concerns related to this pull request.

### CODE REVIEW

**Comment by Nishitbaria** [comment]
@swapnilsparsh ,please review and merge my pull request i have fixed preloader

**Comment by Nishitbaria** [comment]
@swapnilsparsh  , i have added percentage loader ,please review and merge my pull request

**Comment by Nishitbaria** [comment]
@swapnilsparsh , i have added percentage loader ,please review and merge my pull request

**Comment by swapnilsparsh** [comment]
@Nishitbaria Resolve the conflicts.

**Comment by Nishitbaria** [comment]
@swapnilsparsh  done

**Pull request merged**
