### PR TITLE
Added backend Resources

### LINKED ISSUE #311: Adding backend resources in webdev
**Is your feature request related to a problem? Please describe.**
As of now there is only css and illustrator resources are there in the project but i want to add some backend resources like various platform to get free api, and other backend stuuf like api key for their dev journey.

### PR DESCRIPTION
**Pull request by Deepanshu0703**
# Description

Added backend resources-platform tools and APIs. You asked for atleast 10 i added 19. 

## Checklist

- [ ] Tests have been added or updated to cover the changes
- [ ] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
Noo, this was not required.
Lots of changes:-
1. All the resources which you have don't count as backend resources as they all are developers website of different website
2. You have to find backend resources which can be helpful for backend developers
3. Create a new route for backend page and also make new button on navbar.

**Comment by Deepanshu0703** [comment]
Okay I get it

**Comment by Deepanshu0703** [comment]
Will make the changes

**Comment by Deepanshu0703** [comment]
Now i have made some changes and now it looks like this can you please see these screenshots.

image

image

image

**Comment by swapnilsparsh** [comment]
@Deepanshu0703 looking great 👍🏻

**Comment by Deepanshu0703** [comment]
Done with the changes

**Pull request merged**
