### PR TITLE
added hover effects, small UI changes, removed underline

### PR DESCRIPTION
**Pull request by mohittk**
I have added hover effects in some buttons and headings, and made some UI changes, and removed underline from headings.

https://user-images.githubusercontent.com/79041510/135568587-90a5637a-6d2d-440c-9058-58685459f9b2.mp4

### CODE REVIEW

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
Add the hover effect on the heading as it is there on the Github, Twitter, and Discord buttons of the landing page rather than changing the color of the heading.

**Comment by mohittk** [comment]
> Add the hover effect on the heading as it is there on the Github, Twitter, and Discord buttons of the landing page rather than changing the color of the heading.

Sure ! will do.

**Comment by mohittk** [comment]
@swapnilsparsh Please checkout requested changes!

**Comment by swapnilsparsh** [comment]
@mohittk Thank you for your contribution. Looking forward to more such amazing contributions :)

**Pull request merged**
