### PR TITLE
Added 'Call to Action' button

### LINKED ISSUE #4: Add a Call to Action Button on Landing Page
When clicking on Call to Action it should scroll down to the Ambassador section.

### PR DESCRIPTION
**Pull request by tnmyk**
Closes #4 .

### CODE REVIEW

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
Few Changes:
1. Rename the button to Explore all.
2. Use the hover effect like the Explore all button on the Ambassador page.

**Comment by tnmyk** [comment]
Can you resolve the conflicts?

**Comment by swapnilsparsh** [comment]
@tnmyk Please resolve this.

**Comment by swapnilsparsh** [comment]
@tnmyk  Thank you for your contribution. Looking forward to more such amazing contributions :)

**Pull request merged**
