### PR TITLE
Changed description for all components of landing page

### PR DESCRIPTION
**Pull request by poorvijn**
Solves issue #190

### CODE REVIEW

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
You have to change the description of the respective sections which are there in Navbar

**Comment by poorvijn** [comment]
Oh I'm sorry I forgot about those
Will do them as soon as possible

**Comment by swapnilsparsh** [comment]
> Oh I'm sorry I forgot about those
> Will do them as soon as possible
> 
> Would you prefer to keep the descriptions for the specific pages same as that of the landing page? 

Yes

**Comment by poorvijn** [comment]
okay, I've changed them accordingly

**Pull request merged**
