### PR TITLE
Added hackathon on Landing page

### LINKED ISSUE #376: Hackathon Description in Landing Page
**Is your feature request related to a problem? Please describe.**
Yes, As like other features like backend , web dev and other you have description of them on the landing page but there is not description of Hackathon on Landing Page.

**Describe the solution you'd like**
I want to add the png image related to hackathon and a short description as given in other features.

image

### PR DESCRIPTION
**Pull request by Deepanshu0703**
# Description

Yes, As like other features like backend , web dev and other you have description of them on the landing page but there is not description of Hackathon on Landing Page.

## Fixes #376 

Replace `issue_no` with the issue number which is fixed in this PR

## Screenshots

image

## Checklist

- [ ] Tests have been added or updated to cover the changes
- [ ] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by swapnilsparsh** [comment]
@Deepanshu0703 Use svg which you have to use SVG. Don't use PNG

**Comment by Deepanshu0703** [comment]
@swapnilsparsh  Corrected that.

**Comment by Deepanshu0703** [comment]
do you find that earlier png image good, if yes then i will change it to svg.

**Comment by swapnilsparsh** [comment]
> do you find that earlier png image good, if yes then i will change it to svg.

Yes, that was good.

**Comment by Deepanshu0703** [comment]
Hey @swapnilsparsh  why you closed this issue I was working on it

**Comment by swapnilsparsh** [comment]
@Deepanshu0703 As you were inactive so it is closed now.

**Comment by Deepanshu0703** [comment]
I was finding the avg image as there are very less images can you reopen it so that I can add the changes

**Comment by swapnilsparsh** [comment]
@Deepanshu0703 It is already fixed #404

**Pull request closed without merging**
