### PR TITLE
Tried to improve scroll to top UI

### PR DESCRIPTION
**Pull request by tnmyk**

### CODE REVIEW

**Comment by tnmyk** [comment]
Closes #5 . Let me know if you want any  changes to be made!

**Comment by swapnilsparsh** [comment]
> Closes #5 . Let me know if you want any changes to be made!

Perfect 🥂

**Comment by swapnilsparsh** [comment]
@tnmyk Thank you for your contribution. Looking forward to more such amazing contributions :)

**Comment by tnmyk** [comment]
Thank you !  😁

**Pull request merged**
