### PR TITLE
Added hover effect in navbar

### PR DESCRIPTION
**Pull request by gokhalevedant06**

### CODE REVIEW

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
Please do the required changes:
While hovering on the Option, the color of the block should change to white for that option and font.

**Comment by gokhalevedant06** [comment]
Screenshot (884)
Will this work ?

**Comment by swapnilsparsh** [comment]
> Screenshot (884) Will this work ?

Take inspiration from Elastic Navbar.

**Comment by gokhalevedant06** [comment]
Screenshot (885)
What about this ?

**Comment by swapnilsparsh** [comment]
> Screenshot (885) What about this ?

Sorry, nope.

**Comment by gokhalevedant06** [comment]
Can you share an example of an elastic navbar?

**Comment by swapnilsparsh** [comment]
> Can you share an example of an elastic navbar?

Try to Google it, you will find it as there are many options in the elastic navbar.

**Comment by gokhalevedant06** [comment]
Screenshot (887)
Found this

**Comment by swapnilsparsh** [comment]
> Screenshot (887) Found this

It's not sticky, I think.

**Comment by gokhalevedant06** [comment]
I am not able to understand how exactly you want it to be

**Comment by gokhalevedant06** [comment]
Do I need to close the PR  ? I am new to open source

**Comment by swapnilsparsh** [comment]
> Do I need to close the PR ? I am new to open source

Look after the issue first, if you are comfortable then only ask for assigning.
Best of luck for the Hacktoberfest 2021.

**Pull request closed without merging**
