### PR TITLE
Footer

### PR DESCRIPTION
**Pull request by Soumyajit2825**
Added the footer for the website as per requirement
Thank You for your concern @swapnilsparsh 
This closed the issue #162

### CODE REVIEW

**Comment by Soumyajit2825** [comment]
@swapnilsparsh there were some merge conflicts issues. I have resolved them and done the PR
Thank You

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
Footer is not responsive in mobile phones.

**Comment by Soumyajit2825** [comment]
> Footer is not responsive in mobile phones.

OK i will work on this

**Comment by Soumyajit2825** [comment]
@swapnilsparsh I have done some changes to make it responsive 
I am not so good in dealing with media queries
I'm sorry for this 😢 
Tried my best
Thank you for your feedback and guidance @swapnilsparsh

**Comment by swapnilsparsh** [comment]
> @swapnilsparsh I have done some changes to make it responsive 
> I am not so good in dealing with media queries
> I'm sorry for this 😢 
> Tried my best
> Thank you for your feedback and guidance @swapnilsparsh 

Great efforts 😃

**Comment by Soumyajit2825** [comment]
> > @swapnilsparsh I have done some changes to make it responsive
> > I am not so good in dealing with media queries
> > I'm sorry for this 😢
> > Tried my best
> > Thank you for your feedback and guidance @swapnilsparsh
> 
> Great efforts 😃

Thank You @swapnilsparsh

**Pull request merged**
