### PR TITLE
Added Filters In Ambassador and Programs Section

### PR DESCRIPTION
**Pull request by Nishitbaria**
# Description

This pull request adds filtering functionality based on labels in the Ambassador and Programs sections of the project.

## Screenshots
Ambassador
Programs

- Added filtering logic to the Ambassador section to allow users to filter ambassadors based on their expertise or location using labels.
- Implemented filtering feature in the Programs section to enable users to filter programs based on specific categories using labels.

## Checklist

- [x] Tests have been added or updated to cover the changes
- [x] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by swapnilsparsh** [comment]
@Nishitbaria Everything is perfect, just remove the filters from ambassador and only one that is "only-female" ambassador program.

**Comment by Nishitbaria** [comment]
> @Nishitbaria Everything is perfect, just remove the filters from ambassador and only one that is "only-female" ambassador program.

means you want me to remove all ambassador filter and put only one filter that is "önly-female"

**Comment by swapnilsparsh** [comment]
> > @Nishitbaria Everything is perfect, just remove the filters from ambassador and only one that is "only-female" ambassador program.
> 
> @swapnilsparsh means you want me to remove all ambassador filter and put only one filter that is "önly-female"

Yes, and make the label for female centric ambassador program also

**Comment by Nishitbaria** [comment]
@swapnilsparsh I have added "Female Centric" filter
image

**Pull request merged**
