### PR TITLE
fixed navbar and footer for darkmode and lightmode

### LINKED ISSUE #393: Navbar and footer for darkmode
### I'm in GSSoC'23

**Describe the bug**
- Navbar and footer doesn't seem to be compatible for the dark mode.

**To Reproduce**
1. Go to 'website'
2. Click on 'darkmode toggle button' and switch to darkmode
3. See the navbar and footer

**Expected behavior**
- Navbar and footer color should be compatible with the dark theme.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by anamika7153**
# Description

Ensured that navbar and footer is compatible for darkmode and light mode

### Light mode:
 | | |
|---|---|
|image |image|
| image | image |
## Checklist

- [x] Tests have been added or updated to cover the changes
- [ ] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

### CODE REVIEW

**Comment by anamika7153** [comment]
@swapnilsparsh please review this PR :)

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
Navbar -> 
image


Footer
image

**Comment by anamika7153** [comment]
> Navbar -> image
> 
> Footer image

@swapnilsparsh What about navbar??
And I just checked again, footer in light seems okay. In light mode, footer content is of white color with light blue background and in darkmode, content is of blue color with darker blue background. Same with navbar.

**Comment by anamika7153** [comment]
@swapnilsparsh deploy preview also seems ok

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
Footer on production website -> 
image

Footer on your preview deployed code
image

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
@anamika7153 In mobile view the color of the fonts of dark mode gets changed.

**Comment by anamika7153** [comment]
> @anamika7153 In mobile view the color of the fonts of dark mode gets changed.

yeah, thanks for the help.

**Comment by anamika7153** [comment]
@swapnilsparsh I have fixed it, you can check now :) I am also updating screenshots

**Comment by anamika7153** [comment]
@swapnilsparsh I have fixed it, you can check now :) I am also updating screenshots

**Comment by anamika7153** [comment]
@swapnilsparsh please review

**Pull request merged**
