### PR TITLE
add contributors page

### LINKED ISSUE #324: add contributors page
**Is your feature request related to a problem? Please describe.**
Creatied a seperate page containing the images and info about contributors of of this project.

**Additional context**

### PR DESCRIPTION
**Pull request by shivaniyuvrajyadav**
# Description

contributors section added on the landing page . 

## Screenshots

https://github.com/swapnilsparsh/DevEmpire/assets/112896644/2e502857-945b-4567-9b8a-75c7a9379c13

## Checklist

- [ ] Tests have been added or updated to cover the changes
- [ ] Documentation has been updated to reflect the changes
- [x ] Code follows the established coding style guidelines
- [ x] All tests are passing

### CODE REVIEW

**Comment by swapnilsparsh** [comment]
@shivaniyuvrajyadav Make the photos small and when clicking on any photo it should redirect to that particular GitHub user account. Resolve the conflict

**Comment by shivaniyuvrajyadav** [comment]
> @shivaniyuvrajyadav Make the photos small and when clicking on any photo it should redirect to that particular GitHub user account. Resolve the conflict

@swapnilsparsh Please review I have made the necessary changes.

**Comment by swapnilsparsh** [comment]
@shivaniyuvrajyadav fix this for a mobile view.

**Comment by Nishitbaria** [comment]
@swapnilsparsh Assign this issue to me I will Fix it

**Comment by shivaniyuvrajyadav** [comment]
@swapnilsparsh please review the changes .

**Comment by swapnilsparsh** [comment]
@shivaniyuvrajyadav Already told you that images will be small, and rebase your branch with the main branch.

**Pull request closed without merging**
