### PR TITLE
Added View More button

### LINKED ISSUE #96: View More button
Add a view more button which should appear on every card and it should redirect to that particular website.

1. Follow the proper [color codes](https://github.com/swapnilsparsh/DevEmpire/blob/master/CONTRIBUTING.md#color-codes-) 
2. UI/UX should be clean.

### PR DESCRIPTION
**Pull request by rockingrohit9639**
Fixed #96

### CODE REVIEW

**Review by swapnilsparsh — CHANGES_REQUESTED** [review]
It's looking cool, just make the heights of all the cards the same, irrespective of content present inside the card.

**Comment by swapnilsparsh** [comment]
@rockingrohit9639 Project has been shifted to Next JS so perform a `git pull` and then make the changes and make a PR 👍🏻

**Comment by rockingrohit9639** [comment]
@swapnilsparsh I have made the changes

**Comment by swapnilsparsh** [comment]
@rockingrohit9639 Thank you for your contribution. Looking forward to more such amazing contributions 🥂

**Pull request merged**
